### ISSUE TITLE
No admin dashboard

### ISSUE THREAD

**Issue by djukaPHP** [sulu/sulu-minimal#149] opened 2019-01-05 21:32 UTC
After install development branch version, frontend work as expected but the admin dashboard is missing, empty white screen, after success login and profiler shows user is anon. Does new version 2.0 uses encore with yarn or npm?

**Comment by alexander-schranz** [comment] 2019-01-06 13:34
Hello @djukaPHP,

Please use the issue template next time.

> Admin dashboard is missing

There is currently no dashboard you should just see the navigation on the left side after login.  Else have a look at your web dev tools if there is any error message.

> Profiler shows user is anon.

Sulu Admin is a single page application aslong as you don't refresh the browser the profiler will not update its status.

> Does new version 2.0  encore with yarn or npm?

we don't use encore. Currently you need to use npm to build the admin js, yarn support is in process sulu/sulu#4306
For your frontend application/website you can use encore or what else you want we recommend not use the same package.json as sulu admin so we currently recommend create a `assets/website/package.json` where my whole website/front application JS/CSS code is build.

**Comment by danrot** [comment] 2019-01-18 09:40
That's actually a duplicate of sulu/sulu#2815, therefore closing it. The dashboard would definitely be interesting, but until now there were always more important things to do. I think what we are going to do in the meantime before the Sulu 2.0 release is to redirect to another view (we are currently thinking about the webspace overview).

**Closed as completed by danrot** 2019-01-18 09:40 UTC
Labels: help wanted
