### ISSUE TITLE
Can't create pages in russian language

### ISSUE THREAD

**Issue by codeh4nter** [sulu/sulu-minimal#42] opened 2017-04-12 23:25 UTC
Sure that there are some problems with "Resource locator" auto generating. Is there any possibility to turn of generating of this field?

**Comment by danrot** [comment] 2017-04-14 08:29
That's a duplicate of https://github.com/sulu/sulu-standard/issues/698.

Are you only using russian as a language? I think it's only a problem then. If you create the page in `en` first it should work. We also have installations with e.g. japanese or chinese as a language, in these cases it's also no problem, because it's not the primary language... I know that's just a workaround 😕 But keep an eye on the other issue.

**Closed as completed by danrot** 2017-04-14 08:29 UTC
